AddMisData(1, "Welcome!", MIS_TREENODE_HISTORY)
AddMisData(2, "New place", MIS_TREENODE_HISTORY)
AddMisData(3, "First acquaintance", MIS_TREENODE_HISTORY) 
AddMisData(4, "Fairy provisions", MIS_TREENODE_HISTORY)
AddMisData(5, "Secretary", MIS_TREENODE_HISTORY) 
AddMisData(10, "Old Jack", MIS_TREENODE_HISTORY) 
AddMisData(11, "Crabs", MIS_TREENODE_HISTORY) 
AddMisData(12, "Where are my tools?", MIS_TREENODE_HISTORY) 
AddMisData(13, "Report to Salvier", MIS_TREENODE_HISTORY) 
AddMisData(14, "Mines", MIS_TREENODE_HISTORY) 
AddMisData(15, "Missing people", MIS_TREENODE_HISTORY) 
AddMisData(16, "Immersion", MIS_TREENODE_HISTORY) 
AddMisData(17, "Mysterious door", MIS_TREENODE_HISTORY) 
AddMisData(18, "Legendary artifact", MIS_TREENODE_HISTORY) 
AddMisData(19, "Mines’ closure", MIS_TREENODE_HISTORY) 
AddMisData(20, "Meet Sinbad", MIS_TREENODE_HISTORY) 
AddMisData(21, "Getting to know the blueprints", MIS_TREENODE_HISTORY) 
AddMisData(22, "Acquaintance with Wood", MIS_TREENODE_HISTORY) 
AddMisData(23, "Pine trees", MIS_TREENODE_HISTORY) 
AddMisData(24, "Ingredients for Sinbad", MIS_TREENODE_HISTORY) 
AddMisData(25, "Manufacture", MIS_TREENODE_HISTORY) 
AddMisData(26, "Grandmother Granny", MIS_TREENODE_HISTORY) 
AddMisData(27, "Acquaintance with Fishing", MIS_TREENODE_HISTORY) 
AddMisData(28, "First fish", MIS_TREENODE_HISTORY) 
AddMisData(29, "There is fish, so you can eat it", MIS_TREENODE_HISTORY) 
AddMisData(30, "Cooking", MIS_TREENODE_HISTORY) 
AddMisData(31, "You are ready", MIS_TREENODE_HISTORY) 
AddMisData(32, "Danger", MIS_TREENODE_HISTORY) 
AddMisData(33, "Village on fire", MIS_TREENODE_HISTORY) 
AddMisData(34, "Leader’s head", MIS_TREENODE_HISTORY) 
AddMisData(35, "Smuggling", MIS_TREENODE_HISTORY) 
AddMisData(36, "They want to see you", MIS_TREENODE_HISTORY) 
AddMisData(37, "Unusual request", MIS_TREENODE_HISTORY) 
AddMisData(56, "Talk with Pet Tamer", MIS_TREENODE_HISTORY) 
AddMisData(38, "It’s time to eat", MIS_TREENODE_HISTORY) 
AddMisData(39, "Mount", MIS_TREENODE_HISTORY) 
AddMisData(40, "Head of Navy", MIS_TREENODE_HISTORY) 
AddMisData(41, "Ghost ship", MIS_TREENODE_HISTORY) 
AddMisData(42, "Cursed sailors", MIS_TREENODE_HISTORY) 
AddMisData(43, "Cursed Blade", MIS_TREENODE_HISTORY) 
AddMisData(44, "Broken Chains", MIS_TREENODE_HISTORY) 
AddMisData(45, "No rest for the dead", MIS_TREENODE_HISTORY) 
AddMisData(46, "Whispers of the Dead", MIS_TREENODE_HISTORY) 
AddMisData(47, "The Shackles of Curse", MIS_TREENODE_HISTORY) 
AddMisData(48, "A power that my father never ever dreamed of", MIS_TREENODE_HISTORY) 
AddMisData(49, "Helping the blacksmith", MIS_TREENODE_HISTORY) 
AddMisData(50, "Disassembly of items", MIS_TREENODE_HISTORY) 
AddMisData(51, "Crafting", MIS_TREENODE_HISTORY) 
AddMisData(52, "Report to the head of navy", MIS_TREENODE_HISTORY) 
AddMisData(100, "Introducing Grany Nila", MIS_TREENODE_HISTORY) 
AddMisData(101, "Upgrade equipment", MIS_TREENODE_HISTORY) 
AddMisData(102, "Go back to Dessaro", MIS_TREENODE_HISTORY) 
AddMisData(103, "The Zephyr Archipelagos", MIS_TREENODE_HISTORY) 
AddMisData(104, "Ïîäãîòîâêà ê Ñòóæå", MIS_TREENODE_HISTORY) 
AddMisData(105, "Socket under gem", MIS_TREENODE_HISTORY) 
AddMisData(106, "Fusion gem", MIS_TREENODE_HISTORY) 
AddMisData(107, "Report", MIS_TREENODE_HISTORY) 
AddMisData(108, "Ïèðàòñêàÿ õîëåðà", MIS_TREENODE_HISTORY) 
AddMisData(109, "Preparation", MIS_TREENODE_HISTORY) 
AddMisData(110, "Upgrade equipment: Efficiency", MIS_TREENODE_HISTORY) 
AddMisData(111, "Your ready", MIS_TREENODE_HISTORY) 
AddMisData(112, "Island of Gold Roger: Good Luck", MIS_TREENODE_HISTORY) 
AddMisData(501, "A trivial task", MIS_TREENODE_DAILY) 
AddMisData(502, "Hunting for a new mount", MIS_TREENODE_DAILY) 
AddMisData(503, "Rare catch", MIS_TREENODE_DAILY) 
AddMisData(504, "Combination", MIS_TREENODE_DAILY) 
AddMisData(505, "Forging", MIS_TREENODE_DAILY) 
AddMisData(506, "Improving equipment", MIS_TREENODE_DAILY) 
AddMisData(507, "Improving", MIS_TREENODE_DAILY) 
AddMisData(508, "Beginner's manufacture", MIS_TREENODE_DAILY) 
AddMisData(509, "Manufacture of the experienced", MIS_TREENODE_DAILY) 
AddMisData(510, "Manufacture expert", MIS_TREENODE_DAILY) 
AddMisData(511, "Help", MIS_TREENODE_DAILY) 
AddMisData(512, "Culinary Basics", MIS_TREENODE_DAILY) 
AddMisData(513, "Culinary Master", MIS_TREENODE_DAILY) 
AddMisData(514, "Culinary guru", MIS_TREENODE_DAILY) 
AddMisData(515, "A dozen crucian carps", MIS_TREENODE_DAILY) 
AddMisData(516, "Fishing time", MIS_TREENODE_DAILY) 
AddMisData(517, "Advanced Fishing", MIS_TREENODE_DAILY) 
AddMisData(518, "Trophy fish", MIS_TREENODE_DAILY) 
AddMisData(519, "Resources", MIS_TREENODE_DAILY) 
AddMisData(520, "Resources", MIS_TREENODE_DAILY) 
AddMisData(521, "First level craft", MIS_TREENODE_DAILY) 
AddMisData(522, "Craft for advanced", MIS_TREENODE_DAILY) 
AddMisData(523, "A challenging craft task", MIS_TREENODE_DAILY) 
AddMisData(524, "Initial research", MIS_TREENODE_DAILY) 
AddMisData(525, "Adventurer's Research", MIS_TREENODE_DAILY) 
AddMisData(526, "Wandering soul", MIS_TREENODE_DAILY) 
AddMisData(527, "Initial research", MIS_TREENODE_DAILY) 
AddMisData(528, "Adventurer's Research", MIS_TREENODE_DAILY) 
AddMisData(529, "Initial research", MIS_TREENODE_DAILY) 
AddMisData(530, "Mines", MIS_TREENODE_DAILY) 
AddMisData(531, "Archipelago of the Cold", MIS_TREENODE_DAILY) 
AddMisData(532, "Damned Therans", MIS_TREENODE_DAILY) 